"""Initial migration

Revision ID: 1c1ed1807ed7
Revises: 
Create Date: 2024-08-16 13:55:46.361401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1ed1807ed7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caretask_table',
    sa.Column('caretask_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('caretask_id')
    )
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.alter_column('breed',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('birthdate',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('birthdate',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('breed',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    op.drop_table('caretask_table')
    # ### end Alembic commands ###
